'use strict';
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const elements = new Map();
const element = (id) => {
  if (!elements.has(id)) elements.set(id,{innerHTML:'',textContent:'',value:'',hidden:false,disabled:false,style:{},classList:{toggle(){}}});
  return elements.get(id);
};
const context = {URL,document:{getElementById:element,querySelectorAll:()=>[]}};
const sourceCode = fs.readFileSync(path.join(__dirname,'../static/app.js'),'utf8');
const testCode = sourceCode.replace('  bindEvents(); showPage(location.hash.slice(1)', '  globalThis.testHooks = {sourceMatches, effectiveOpinions, rankThemes, safeSourceURL, filters, renderDashboard, renderImports, renderBudget, renderHistory, renderSpans, renderRouting, renderRoutingEditor, prepareOpinion, reviewSchema, validateOpinion, insightSummary, timelineRows, renderEditors, setEditors: value => {editors=value;}, setState: value => {state=value;}}; return;\n  bindEvents(); showPage(location.hash.slice(1)');
assert.notEqual(sourceCode,testCode,'test hooks inserted before application startup');
vm.createContext(context); vm.runInContext(testCode,context);
const t=context.testHooks;
assert.equal(t.safeSourceURL('javascript:alert(1)'), '');
assert.equal(t.safeSourceURL('https://example.com/a'),'https://example.com/a');
const emptyState={sources:[],opinions:[],batches:[],job:{running:false,status:'idle'},settings:{monthly_budget:20},budget:{remaining:20,spent:0,reserved:0,month:'2026-09'},ledger:[]};
t.setState(emptyState); t.renderDashboard(); t.renderImports(); t.renderBudget();
assert.match(element('results-list').innerHTML,/还没有有效观点/);
assert.match(element('module-grid').innerHTML,/语音助手（lumo）/);
assert.match(element('side-remaining').textContent,/20.00/);
const source={key:'a',kind:'comment',title:'',text:'lumo <img src=x onerror=alert(1)> 很好',status:'done',manual:false,relevance:'relevant',review_status:'unreviewed',published_at:'2026-09-01T00:00:00Z',batch_ids:['batch-a'],note_id:'note-1'};
const other={...source,key:'b',manual:true,status:'pending',note_id:'note-2'};
const pending={...source,key:'c',manual:false,status:'pending'};
const irrelevant={...source,key:'d',relevance:'irrelevant'};
const op={module:'语音助手（lumo）',type:'体验评价',sentiment:'正面',theme:'语音识别',evidence:source.text};
t.setState({...emptyState,sources:[source,other,pending,irrelevant],opinions:[{...op,id:'1',source_key:'a'},{...op,id:'2',source_key:'a'},{...op,id:'3',source_key:'b'},{...op,id:'4',source_key:'c'},{...op,id:'5',source_key:'d'},{...op,id:'6',source_key:'a',module:'其他',theme:'价格'}]});
assert.equal(t.effectiveOpinions().length,3,'protect effective manual result while body is pending');
pending.has_analysis = true;
assert.equal(t.effectiveOpinions().length,4,'keep previous AI result when updated content is pending');
pending.has_analysis = false;
assert.equal(t.rankThemes(t.effectiveOpinions())[0].sources.size,2,'source counts must deduplicate opinions');
assert.equal(t.rankThemes(t.effectiveOpinions())[0].notes.size,2,'comments must count distinct parent notes');
t.renderDashboard();
assert.ok(!element('results-list').innerHTML.includes('<img'));
assert.ok(element('results-list').innerHTML.includes('&lt;img'));
t.filters.module='其他'; assert.equal(t.effectiveOpinions().length,1);
t.filters.module='focus'; t.filters.theme='语音'; assert.equal(t.effectiveOpinions().length,0,'theme is exact, like CSV export');
t.filters.theme=''; t.filters.q='LUMO'; assert.equal(t.effectiveOpinions().length,3);
t.filters.q='语音识别'; assert.equal(t.effectiveOpinions().length,3);
assert.equal(t.sourceMatches(source),false,'source library searches original while opinions also search themes');
t.filters.q=''; t.filters.from='2026-09-02'; assert.equal(t.effectiveOpinions().length,0);
t.filters.from='2026-09-01'; t.filters.to='2026-09-01'; assert.equal(t.effectiveOpinions().length,3);
t.filters.from=''; t.filters.to=''; t.filters.batch='missing'; assert.equal(t.effectiveOpinions().length,0);
const renderedHistory=t.renderHistory({event:'manual_review',created_at:null,snapshot:{source,opinions:[op]}});
assert.ok(!renderedHistory.includes('<img'));
assert.ok(renderedHistory.includes('人工修改前的结果'));
// Synthetic ABSA v2 fixtures; never read production data or call a model.
Object.assign(t.filters,{kind:'comment',module:'focus',sentiment:'',type:'',theme:'',review:'',from:'',to:'',q:'',batch:'',submodule:'',content_type:'',schema:'',needs_review:'',scope:''});
const v2source={...source,key:'v2',text:'语音助手识别太慢，价格太高',analysis_schema:'absa-v2',eligible_for_insights:true,brand_relevance:'related',product_scope:'mixed',content_types:['product_feedback'],review_reasons:['需要核对'],filter_reason:'',has_analysis:true};
const v2op={...op,id:'v2-1',source_key:'v2',schema_version:'absa-v2',submodule:'语音识别',aspect_category:'语音助手（lumo）-语音识别',target_text:'语音助手',opinion_text:'识别太慢',feedback_type:'complaint',sentiment:'负面',sentiment_code:'negative',theme:'语音识别',evidence:'语音助手识别太慢',implicit_target:false,implicit_opinion:false,context_used:false,needs_review:false};
const implicit={...v2op,id:'v2-2',target_text:null,implicit_target:true,needs_review:true};
const excluded={...v2source,key:'excluded',eligible_for_insights:false,content_types:['promotion'],product_scope:'not_applicable'};
const v2state={...emptyState,options:{submodules:{'语音助手（lumo）':['语音识别'],'价格':['价格评价']}},sources:[v2source,excluded,source],opinions:[v2op,implicit,{...v2op,id:'excluded-op',source_key:'excluded'},{...op,id:'old',source_key:'a'},{...v2op,id:'price',module:'价格',submodule:'价格评价',theme:'价格评价',evidence:'价格太高',target_text:'价格',opinion_text:'太高'}]};
t.setState(v2state);
assert.equal(t.effectiveOpinions().length,3,'ineligible v2 source excluded; valid legacy source retained');
assert.equal(t.sourceMatches(excluded),true,'raw library retains excluded sources');
const routedLegacy={...excluded,analysis_schema:'legacy',routing_schema:'absa-v2'};
t.setState({...v2state,sources:[v2source,routedLegacy,source]});
assert.equal(t.effectiveOpinions().length,3,'routed legacy source excluded from insight statistics');
assert.equal(t.sourceMatches(routedLegacy),true,'routed legacy source retained in raw library');
assert.match(t.renderRouting(routedLegacy),/不纳入观点统计/);
t.setState(v2state);
t.filters.schema='absa-v2'; assert.equal(t.effectiveOpinions().length,2);
t.filters.content_type='promotion'; assert.equal(t.effectiveOpinions().length,0);
t.filters.content_type='product_feedback'; t.filters.submodule='语音识别'; assert.equal(t.effectiveOpinions().length,2);
t.filters.needs_review='true'; assert.equal(t.effectiveOpinions().length,1);
assert.equal(t.sourceMatches(v2source),true,'raw library matches any reviewable opinion');
t.filters.needs_review='false'; assert.equal(t.effectiveOpinions().length,1);
t.filters.needs_review=''; t.filters.scope='cockpit'; assert.equal(t.effectiveOpinions().length,0);
t.filters.scope='mixed'; assert.equal(t.effectiveOpinions().length,2);
t.filters.module='价格'; t.filters.submodule=''; assert.equal(t.effectiveOpinions().length,1,'independent non-cockpit group remains available');
Object.assign(t.filters,{module:'focus',schema:'',scope:'',content_type:''});
const preparedOld=t.prepareOpinion(op);
assert.equal(preparedOld.schema_version,'legacy');
assert.equal('target_text' in preparedOld,false,'legacy save must not fabricate spans');
assert.equal('feedback_type' in preparedOld,false,'legacy save retains original feedback type');
const preparedImplicit=t.prepareOpinion({...implicit,target_text:'must not persist',needs_review:false});
assert.equal(preparedImplicit.target_text,null,'implicit spans always serialize to null');
assert.equal(preparedImplicit.needs_review,false,'an implicit target alone does not imply uncertainty');
assert.equal(t.prepareOpinion({...implicit,implicit_opinion:true,opinion_text:null,needs_review:false}).needs_review,true,'implicit opinion needs review');
assert.equal(t.prepareOpinion({...v2op,sentiment:'正面',sentiment_code:'negative'}).sentiment_code,'positive','edited Chinese sentiment updates canonical code');
assert.equal(t.reviewSchema([op,v2op]),'legacy','mixed source preserves legacy schema');
assert.equal(t.reviewSchema([v2op,implicit]),'absa-v2','all v2 opinions upgrade source schema');
assert.equal(t.validateOpinion(preparedImplicit,v2source.text),'');
assert.match(t.validateOpinion({...preparedImplicit,evidence:'不存在的证据'},v2source.text),/逐字/);
assert.match(t.validateOpinion({...t.prepareOpinion(v2op),target_text:'价格'},v2source.text),/逐字片段/);
assert.match(t.validateOpinion({...t.prepareOpinion(v2op),submodule:'价格评价'},v2source.text),/标准子模块/);
assert.match(t.renderSpans(implicit),/隐含对象 · null/);
assert.match(t.renderSpans(op),/旧版观点/);
assert.ok(!t.renderSpans({...v2op,target_text:'<img src=x>'}).includes('<img'));
assert.match(t.renderRouting(excluded),/不纳入观点统计/);
assert.match(t.renderRouting(source),/未补造来源路由/);
assert.match(t.renderRoutingEditor(v2source),/product_feedback/);
t.setEditors([op,v2op,implicit]); t.renderEditors();
assert.match(element('opinion-editors').innerHTML,/补全为 v2/);
assert.match(element('opinion-editors').innerHTML,/含旧版观点/);
assert.match(element('opinion-editors').innerHTML,/上下文推断关闭/);
assert.match(element('opinion-editors').innerHTML,/data-field="target_text"/);
assert.match(element('opinion-editors').innerHTML,/保存为 null/);
const aggregates=[{...v2op,source:v2source},{...implicit,source:v2source},{...op,source_key:'a',source:{...source,published_at:null}}];
assert.equal(t.insightSummary(aggregates).sources,2,'sample denominator deduplicates sources');
assert.equal(t.insightSummary(aggregates).negativeSources,1,'multiple negative opinions count one source');
assert.equal(t.insightSummary(aggregates).negativeShare,0.5);
assert.equal(t.timelineRows(aggregates).length,2,'missing dates retained as their own bucket');
t.renderDashboard();
assert.match(element('other-module-buttons').innerHTML,/销售与服务/);
assert.match(element('issue-list').innerHTML,/代表性证据/);
assert.match(element('timeline-list').innerHTML,/不代表用户赞同/);
assert.match(element('schema-banner').textContent,/不补造抽取片段/);
t.setState({...v2state,analysis_metrics:{requests:2,request_success_rate:0.5,json_success_rate:0,truncation_rate:0.5,retry_rate:0.5,avg_latency_seconds:1,p95_latency_seconds:2,cost:0.01,legacy_requests:3},job:{total:4,completed:4,succeeded:2,failed:1,skipped:1}});
t.renderBudget(); t.renderImports();
assert.match(element('analysis-metrics').innerHTML,/50.0%/);
assert.match(element('metrics-note').textContent,/3 条历史请求/);
assert.match(element('job-status').innerHTML,/成功 2 \/ 失败 1 \/ 跳过 1/);
const html=fs.readFileSync(path.join(__dirname,'../static/index.html'),'utf8');
for(const id of ['filter-submodule','filter-content_type','filter-schema','filter-needs_review','filter-scope','setting-concurrency','setting-reasoning_effort','setting-format_retries','schema-banner','timeline-list','issue-list','analysis-metrics']) assert.ok(html.includes(`id="${id}"`),`UI element ${id} exists`);
assert.ok(html.includes('value="legacy"'),'legacy reanalysis is explicit');
assert.ok(html.includes('env-file-path'),'.env setup retained');
console.log('Frontend assertions passed: legacy preservation, v2 routing and filters, span validation/nulls, safe rendering, editor fields, distinct-source insights, timeline, telemetry, job counters and UI controls.');
